global:
  scrape_interval: 1s  # Interval to scrape metrics

scrape_configs:
  - job_name: 'panth_app'  # Job name is 'panth_app'
    static_configs:
      - targets: ['crontab-app:4000']  # The new endpoint for metrics
